apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: dask-worker
    app: dask
  name: dask-worker
spec:
  replicas: {{workers.count}}
  selector:
    name: dask-worker
  template:
    metadata:
      labels:
        name: dask-worker
        app: dask
    spec:
      containers:
        - name: dask-worker
          image: {{workers.image}}
          args: ["dask-worker", "dask-scheduler:8786", "--nthreads",
                 "{{workers.cpus_per_worker2}}", "--memory-limit",
                 "{{workers.memory_per_worker2}}", "--interface",
                 "eth0"]
          resources:
            requests:
              cpu: {{workers.cpus_per_worker}}
              memory: {{workers.memory_per_worker}}
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
          workingDir: /work
          volumeMounts:
            - mountPath: /data/newman-met-ensemble
              name: newman-met-ensemble
              readOnly: true
      volumes:
        - name: newman-met-ensemble
          # This GCE PD must already exist.
          gcePersistentDisk:
            pdName: newman-met-ensemble
            fsType: ext4
            readOnly: true
