apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: dask-worker
    app: dask
  name: dask-worker
spec:
  replicas: {{workers.count}}
  selector:
    name: dask-worker
  template:
    metadata:
      labels:
        name: dask-worker
        app: dask
    spec:
      containers:
        - name: dask-worker
          image: {{workers.image}}
          args: ["dask-worker", "dask-scheduler:8786", "--nthreads",
                 "{{workers.cpus_per_worker2}}", "--memory-limit",
                 "{{workers.memory_per_worker2}}", "--interface",
                 "eth0"]
          resources:
            requests:
              cpu: {{workers.cpus_per_worker}}
              memory: {{workers.memory_per_worker}}
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
          workingDir: /work
          volumeMounts:
            - mountPath: /data/gfdl-cm2-6
              name: gfdl-cm2-6
              readOnly: true
      volumes:
        - name: gfdl-cm2-6
          # This GCE PD must already exist.
          gcePersistentDisk:
            pdName: gfdl-cm2-6
            fsType: ext4
            readOnly: true
